name: Android Build Final Fix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        # Выкачиваем всю историю (на случай проблем с ветками)
          clean: false          # Не очищаем директорию перед билдом

      - name: Verify Files (Check where we are)
        # Эта команда покажет путь к текущей папке и всё её содержимое
        run: |
          pwd
          ls -la
          ls -R

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          
      - name: Grant execute permission for all gradlew files
        run: find . -name "gradlew" -exec chmod +x {} +
      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses || true
              
      - name: Build Android APK
        # Собираем именно Андроид, а не сервер
        run: ./gradlew build -x lint
        working-directory: ./Andorid

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          # Указываем путь, учитывая твою опечатку в названии папки
          path: Andorid/app/build/outputs/apk/debug/*.apk
